"""
Configuration initialization CLI commands.

Commands for creating configuration templates:
  init config   - Generate pipeline config file
  init defaults - Create default settings file
"""

import click
from pathlib import Path

from eprobe.cli.utils import (
    echo_success,
    echo_error,
    echo_info,
)


POPGEN_CONFIG_TEMPLATE = """\
# eProbe POPGEN Panel Pipeline Configuration
# Generated by: eprobe init config --panel popgen
# Documentation: https://github.com/your-org/eprobe

pipeline:
  name: "POPGEN Probe Design"
  panel: popgen
  description: "Genome-wide SNP capture probes"

# Input files
input:
  vcf: "data/input.vcf.gz"           # VCF file with target SNPs
  reference: "data/reference.fa"      # Reference genome FASTA
  # bed: "data/regions.bed"           # Optional: restrict to regions

# Pipeline steps (comment out to skip)
steps:
  # Step 1: Extract SNPs from VCF
  - extract:
      flank: 60                        # Flanking region length
      cluster_mode: on                 # Remove clustered SNPs
      cluster_flank: 60                # Cluster detection window
      max_cluster_snp: 3               # Max SNPs in cluster

  # Step 2: Filter SNPs
  - filter:
      filters:                         # Enabled filters
        - BG                           # Background noise (Kraken2)
        - biophysical                  # GC, Tm, complexity
      bg_db: "/path/to/kraken2_db"    # Kraken2 database
      # ac_db: "/path/to/bowtie2_idx" # Accessibility (Bowtie2)
      # tx_db: "/path/to/taxa_db"     # Taxonomy filter
      gc_range: [35, 65]              # GC content range (%)
      tm_range: [55, 75]              # Melting temperature range (°C)
      max_complexity: 2.0              # Max DUST complexity score

  # Step 3: Select SNPs
  - select:
      strategy: uniform                # uniform or random
      probe_number: 10000             # Target probe count
      window_size: 100000             # Window size for uniform selection

  # Step 4: Build probes
  - build:
      length: 81                       # Probe length
      shift: 0                         # SNP offset from center
      replace_mode: on                 # Include alternate allele probes

# Optional: Assessment (runs automatically if uncommented)
# assess:
#   tags: [gc, tm, complexity, hairpin, dimer]
#   plot: true

# Resource settings
resources:
  threads: 4
  memory: "8G"                         # Memory limit (if applicable)
"""


FUNCGEN_CONFIG_TEMPLATE = """\
# eProbe FUNCGEN Panel Pipeline Configuration
# Generated by: eprobe init config --panel funcgen
# Documentation: https://github.com/your-org/eprobe

pipeline:
  name: "FUNCGEN Probe Design"
  panel: funcgen
  description: "Targeted gene capture probes"

# Input mode: choose one of fasta, bed, or gff
input:
  mode: fasta                          # fasta, bed, or gff
  
  # For mode: fasta
  fasta: "data/genes.fa"              # Gene sequences
  
  # For mode: bed
  # bed: "data/targets.bed"
  # reference: "data/reference.fa"
  # vcf: "data/variants.vcf.gz"       # Optional: for haplotyping
  
  # For mode: gff
  # gff: "data/annotation.gff3"
  # reference: "data/reference.fa"
  # feature_type: CDS                  # gene, mRNA, CDS, exon
  # gene_list: "data/target_genes.txt" # Optional

# Probe generation settings
settings:
  length: 81                           # Probe length
  step: 30                             # Tiling step size
  
  # Haplotyping (optional)
  haplotyping: false
  haplotype_sep: "_"                   # Separator for allele IDs
  min_freq: 0.05                       # Min haplotype frequency

# Optional: Post-processing
postprocess:
  dedup:
    enabled: true
    method: cdhit
    identity: 0.95

# Optional: Assessment
assess:
  tags: [gc, tm, complexity]
  plot: true

# Resource settings
resources:
  threads: 4
"""


DEFAULTS_TEMPLATE = """\
# eProbe Default Settings
# Place this file at ~/.eprobe/defaults.yaml or in your project directory
# These settings are used when options are not explicitly specified

# Biophysical thresholds
biophysics:
  gc:
    min: 35.0
    max: 65.0
  tm:
    min: 55.0
    max: 75.0
  complexity:
    max: 2.0
  hairpin:
    max: 0.3
  dimer:
    max: 0.5

# Probe generation defaults
probe:
  length: 81
  shift: 0
  replace_mode: true

# Clustering defaults
cluster:
  flank: 60
  max_snp: 3

# Selection defaults
selection:
  window_size: 100000
  strategy: uniform

# Database paths (optional - set once and reuse)
# databases:
#   kraken2:
#     human: "/path/to/k2_human"
#     standard: "/path/to/k2_standard"
#   bowtie2:
#     accessibility: "/path/to/access_idx"
#   taxonomy:
#     ncbi: "/path/to/taxonomy"

# Resource defaults
resources:
  threads: 4
  temp_dir: "/tmp/eprobe"

# Output preferences
output:
  compression: gzip
  log_level: INFO
  plots: true
"""


@click.group()
@click.pass_context
def init(ctx: click.Context) -> None:
    """
    Generate configuration templates.
    
    Create template configuration files to customize eProbe pipelines.
    
    \b
    Available templates:
      config   - Pipeline configuration file
      defaults - Default settings file
    """
    pass


@init.command()
@click.option(
    "-o", "--output",
    required=True,
    type=click.Path(path_type=Path),
    help="Output file path.",
)
@click.option(
    "--panel",
    type=click.Choice(["popgen", "funcgen"]),
    default="popgen",
    help="Panel type (default: popgen).",
)
@click.option(
    "--force/--no_force",
    default=False,
    help="Overwrite existing file.",
)
@click.pass_context
def config(
    ctx: click.Context,
    output: Path,
    panel: str,
    force: bool,
) -> None:
    """
    Generate pipeline configuration template.
    
    Creates a YAML template with all available options and
    documentation comments.
    
    \b
    Example:
      eprobe init config -o my_pipeline.yaml --panel popgen
      eprobe init config -o funcgen.yaml --panel funcgen
    """
    if output.exists() and not force:
        echo_error(f"File exists: {output}")
        echo_info("Use --force to overwrite")
        raise SystemExit(1)
    
    template = POPGEN_CONFIG_TEMPLATE if panel == "popgen" else FUNCGEN_CONFIG_TEMPLATE
    
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(template)
    
    echo_success(f"Created {panel.upper()} config template: {output}")
    echo_info("Edit the file to configure your pipeline, then run:")
    echo_info(f"  eprobe run pipeline -c {output} -o results/")


@init.command()
@click.option(
    "-o", "--output",
    type=click.Path(path_type=Path),
    default=Path("~/.eprobe/defaults.yaml"),
    help="Output file path (default: ~/.eprobe/defaults.yaml).",
)
@click.option(
    "--force/--no_force",
    default=False,
    help="Overwrite existing file.",
)
@click.pass_context
def defaults(
    ctx: click.Context,
    output: Path,
    force: bool,
) -> None:
    """
    Generate default settings file.
    
    Creates a defaults.yaml file with all configurable defaults.
    This file can be placed in ~/.eprobe/ for global settings or
    in your project directory for project-specific settings.
    
    \b
    Priority order (highest to lowest):
      1. Command-line arguments
      2. Pipeline config file
      3. Project defaults.yaml
      4. User defaults (~/.eprobe/defaults.yaml)
      5. Built-in defaults
    """
    output = output.expanduser()
    
    if output.exists() and not force:
        echo_error(f"File exists: {output}")
        echo_info("Use --force to overwrite")
        raise SystemExit(1)
    
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(DEFAULTS_TEMPLATE)
    
    echo_success(f"Created defaults file: {output}")
    echo_info("Edit the file to customize default settings")
